### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by Rudloff** [sunnywalker/jQuery.FilterTable#34]
Hello,

It would be nice to have a bower.json file for this library.

Regards,

**Comment by sunnywalker** [comment]
I don't use bower and am not familiar with its functionality. Would you be willing to make a pull request?

**Comment by Rudloff** [comment]
Here it is: https://github.com/sunnywalker/jQuery.FilterTable/pull/37

**Comment by sunnywalker** [comment]
Thank you!
