### ISSUE TITLE
Sorting on table column?

### ISSUE THREAD

**Issue by GoodLookin** [sunnywalker/jQuery.FilterTable#41]
Nice script! Is there any chance of adding sorting functionality? I am using it on a pricing table and would love to be able to sort the filtered results by the pricing column.

Thanks

**Comment by sunnywalker** [comment]
I strongly suggest you use a plugin specifically written for table sorting. I just did a quick test with http://tablesorter.com/docs/ and it worked in conjunction with jQuery.FilterTable.
