### ISSUE TITLE
default minRows to 0

### ISSUE THREAD

**Issue by emilv** [sunnywalker/jQuery.FilterTable#42]
I have just spent an unhealthy amount of time troubleshooting the same problem as in https://github.com/sunnywalker/jQuery.FilterTable/issues/26.

filterTable did show up for one of our tables but not for the other, with the same code. I read the JS console, tried to run .filterTable() manually in the console, saw that there were no additions to the DOM, checked that the plugin was called at all, read the, in my mind, important introduction in the manual over and over. I did not expect to find a `minRows` setting that defaults to hiding everything.

I suspect most users don't like when DOM elements are sometimes there and sometimes not.

My suggestion is to either default `minRows` to `0` or to at least add a message with `console.log` when the table is skipped. What do you think?

**Comment by sunnywalker** [comment]
I'm hesitant to making a "breaking" change which will cause different behavior to all those sites with the currently deployed defaults. But I see your point--in fact, it's the reason for FAQ #2 in the FAQ file. At the very least, highlighting that FAQ or at least the file in the main readme is in order. Do you think that would have reduced some of your frustration?

**Comment by emilv** [comment]
Linking or including the FAQ on [this page](http://sunnywalker.github.io/jQuery.FilterTable/) would have helped a lot, yes :-)

**Comment by DevStrefa** [comment]
I am with @emilv, today I spent some time figuring out what is wrong with my code :), after few tries I downloaded full version and after analyzing code I saw this minRows: 8. I know that BC breaks are bad but this information should be somewhere on frontpage.

**Comment by sunnywalker** [comment]
I'm sorry for the trouble and I've added a reference to the FAQ on the main index page in the new version.
