### ISSUE TITLE
pass in a url variable?

### ISSUE THREAD

**Issue by suzigrishpul** [sunnywalker/jQuery.FilterTable#54]
hey there! great plugin. question - is it possible to pre-set the filter by passing in a get variable from the url?

thanks!

**Comment by sunnywalker** [comment]
Sorry, this isn't built into the plugin. You may be able to do it outside of the plugin if you use an existing input (see the example for this) and pre-fill your existing input from `location.hash.substring(1)` (e.g., `example.com/page/#my-filter`) before invoking the `$('table').filterTable()` plugin. This is probably not be the best solution, but it might work.

Edit: or of course pre-fill the existing input via a server-side script.
